services:
  db:
    image: postgres:15-alpine
    container_name: fornogestor-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fornogestor-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fornogestor-api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fornogestor-network
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  postgres_data:

networks:
  fornogestor-network:
    driver: bridge
